---
title: "include"
author: "Chris Tufts"
date: "Thursday, February 12, 2015"
output: html_document
---

A short description of the features and response of the dataset are provided in the list below. 

1. (age): Age of the patient
2. (sex): Sex of the patient
3. (cp):  chest pain type - factor    
4. (trestbps):  resting blood pressure 
5. (chol):  serum cholesterol 
6. (fbs): fasting blood sugar > 120 mg/dl  
  - 1 = true
  - 0 = false
7. (restecg): resting electrocardiographic results
  - Value 0: normal
  - Value 1: having ST-T wave abnormality (T wave inversions and/or ST 
                                           elevation or depression of > 0.05 mV)
  - Value 2: showing probable or definite left ventricular hypertrophy
                       by Estes' criteria
8. (thalach): maximum heart rate achieved
9. (exang): exercise induced angina
  - 1 = yes
  - 0 = no
10. (oldpeak): ST depression induced by exercise relative to rest
11. (slope): the slope of the peak exercise ST segment
  - Value 1: upsloping
  - Value 2: flat
  - Value 3: downsloping     
12. (ca): number of major vessels colored by flourosopy
  - encoded with integers 0-3 colored by flourosopy   
13. (thal): No explanation provided by UCI data descriptions
  - 3 = normal
  - 6 = fixed defect
  - 7 = reversable defect     
14. (num):  diagnosis of heart disease (angiographic disease status)
  - Value 0: < 50% diameter narrowing
  - Value 1: > 50% diameter narrowing
